/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.us.mwm.twitter.gui;

import es.us.mwm.twitter.client.TwitterClient;
import es.us.mwm.twitter.entities.friendsTimeline.Status;
import es.us.mwm.twitter.entities.tweets.Tweet;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author master
 */
public class Elemento extends javax.swing.JPanel implements ListCellRenderer<Tweet> {

    /**
     * Creates new form Elemento
     */
    public Elemento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelPic = new javax.swing.JLabel();

        jLabel1.setLabelFor(jTextPane1);
        jLabel1.setText("Usuario");

        jScrollPane1.setViewportView(jTextPane1);

        jLabelPic.setText("jLabel2");
        jLabelPic.setMaximumSize(new java.awt.Dimension(48, 48));
        jLabelPic.setMinimumSize(new java.awt.Dimension(48, 48));
        jLabelPic.setName(""); // NOI18N
        jLabelPic.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public java.awt.Component getListCellRendererComponent(JList<? extends Tweet> list, Tweet value, int index, boolean isSelected, boolean cellHasFocus) {

        jTextPane1.setText(value.getText());
        jLabel1.setText("<html>" + value.getUser().getName() + "</html>");

        TwitterClient cliente = new TwitterClient();

        //ESTO ES PARA INTENTAR PONER LOS AVATARES DE LOS USUARIOS QUE ESTAN EN MI MURO
        String iconSrc = value.getUser().getProfile_image_url();
        URL iconURL = null;
        try {
            iconURL = new URL(iconSrc);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Elemento.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon img = new ImageIcon(iconURL, value.getUser().getName());
        jLabelPic.setIcon(img);

        return this;
    }

}
